---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# PFSC

<!-- badges: start -->
<!-- badges: end -->

The PFSC package provides functions to simulate the remainder of prematurely stopped soccer leagues. It calculates for each team the probabilities to reach each position in the final league table.

## Installation

You can install this package from [GitHub](https://github.com/) with:

```{r, echo=T, eval=F}
# install.packages("devtools")
devtools::install_github("vaneetvelde/PFSC")
```

## Example

We give the example of the stopped season of the French first ligue in 2019-2020.
```{r example}
library(PFSC)
results<-read.csv("https://www.football-data.co.uk/mmz4281/1920/F1.csv")
results<-results[,4:7]
colnames(results)<-c("home_team","away_team","home_score","away_score")

# The intermediate league table
table1<-league_table(results)
table1

# The estimated team strengths
ratings<-team_ratings(results)$ratings
ratings

# The probabistic final standing
PFS_France<-simulate_league(results, S=10000)
PFS_France

```

